import {
  DEFAULT_LOCAL_SESSION_LIST_LIMIT,
  MAX_LOCAL_SESSION_LIST_LIMIT,
} from './aliases.js';

export function buildHelpCommandResponse(): string {
  return [
    '**命令速览**',
    '',
    '**运维**',
    '- `/` 当前聊天/当前会话诊断',
    '- `/status` 全局状态（通道、Bridge/UI 进程、PID、绑定与会话数量）',
    '- `/check` 或 `/health` 健康检查',
    '- `/check all` 查看所有运行中会话的健康状态',
    '- `/doctor [bridge_id:<id>|<id>] [时间点/描述]` 把目标 id、故障描述和结构化 JSONL bridge.log 路径交给当前会话诊断；参数可省略，不会把整段日志贴进上下文',
    '- `/his` 最近消息卡片（等同 `/his msg`，优先 Codex / Claude Code / Kimi Code / Cursor 本地 session 文件，找不到再读 Bridge 缓存）',
    '- `/his msg [1-20]` 最近消息卡片，可临时指定本次条数',
    '- `/his raw [1-20]` 解析后的纯文本视图，可临时指定本次条数',
    '- `/his json` 直接发送原始 session JSONL 文件（兼容别名：`/his file`）',
    '- `/his limit 12` 修改 `/his msg` 默认返回条数（1-20）',
    '- `/hot-update` 使用当前 Bridge 环境派发本项目热更新，并每 3 秒刷新 hot update log 卡片，只展示最后 100 行；`/hot-update --dry-run` 只检查不执行',
    '',
    '**Bridge 控制**',
    '- `//...` 向模型发送以 `/` 开头的文本',
    '- `/h` 帮助',
    '- `/provider` 或 `/p` 查看或切换当前 runtime 的 Provider（使用何种方式运行 agent）；Codex 可用 `sdk | pty | tmux`，Claude 可用 `tmux | pty | sdk` 且默认 `tmux`，Kimi 与 Cursor 固定 `tmux`',
    '- `/stop` 停止当前任务',
    `- \`/t\` 默认显示当前 runtime 最近 ${DEFAULT_LOCAL_SESSION_LIST_LIMIT} 条本地会话；卡片是一张表，可用数量下拉切换 20/50/100，也可用 runtime 下拉切换 Codex/Claude/Kimi/Cursor`,
    `- \`/t all\` 最多显示当前 runtime 最近 ${MAX_LOCAL_SESSION_LIST_LIMIT} 条本地会话`,
    `- \`/t n 50\` / \`/t n 100\` 调整当前 runtime 本地会话显示数量；也可用 \`/t codex n 100\`、\`/t claude n 100\`、\`/t kimi n 100\` 或 \`/t cursor n 100\``,
    '- `/t 1` 接管第 1 条会话，并设为当前线程；接管其他聊天已绑定的会话需要确认，目标正在运行时不能接管',
    '- `/t` 卡片首列会标出当前激活的对话和其他人激活的对话，bridge_id 存在表示曾经接入过 codelark',
    '- `/t archive` 归档当前本地会话并解除相关绑定；也可用 `/t archive 1` 按当前 runtime 的 `/t` 表序号指定会话',
    '- `/t unbind` 将当前聊天从现有会话解绑，并立即绑定到新的临时 BridgeSession；之后接管已有会话时会自动删除该临时 BridgeSession',
    '- `/t rename <名称>` 重命名当前线程；群聊通道会同步修改群聊名称并自动带 `[botname]` 前缀',
    '- 序号范围：`/t 1` 和 `/t archive 1` 使用当前 runtime 的 `/t` 本地会话表',
    '- `/t 0` 临时 BridgeSession',
    '- `/t 0 reset` 重置临时 BridgeSession',
    '- `/n` 打开新建 IM 群聊会话表单；`/new <name> [path]` 直接创建，未指定路径时继承当前会话目录，包括临时 BridgeSession 目录，未绑定时使用全局默认工作目录；在飞书云文档评论里 @bot 会直接把这份云文档切到群聊聊天模式，默认目录使用全局默认工作目录，默认群名为 `doc:<文档标题前缀>`，不会弹表单；名称或路径包含空格时，请使用英文双引号 `"` 或英文单引号 `\'`',
    '- `/clear [name] [path]` 在当前聊天上下文创建新对话并绑定过去；名称或路径包含空格时，请使用英文双引号 `"` 或英文单引号 `\'`；可用 `/t` 附回旧对话；当前任务或 tmux TUI 追加输入运行中会先询问是否终止',
    '- `/require-at` 查看飞书群聊 @bot 要求；`/require-at on|off` 切换当前飞书通道是否要求群聊 @bot',
    '- 直接发文本：继续当前会话；未绑定时进入临时 BridgeSession',
    '',
    '**终端工具**',
    '- `/shell [秒数] <command>`（新特性）在当前会话目录用 `codex sandbox` 流式执行命令；默认允许网络；卡片刷新最低 5 秒；高风险命令需追加 `--force`',
    '- `/shell --sandbox read-only|workspace-write [秒数] <command>` 指定本次 shell sandbox；不允许 danger-full-access；IM 自动链接会按显示文本执行',
    '- `/tmux-switch` 列出 tmux sessions，类似 `Ctrl+b s`',
    '- `/tmux-attach <session>` 绑定当前 IM 会话的远程 tmux session',
    '- `/tmux-new [session]` 新建并绑定 tmux session；已存在则提示并直接绑定',
    '- `/tmux-status` 查看当前绑定和截屏行数',
    '- `/tmux-set lines 120` 设置 `/tmux` 自动截屏行数',
    '- `/tmux-screen [lines] [seconds]s` 查看当前绑定 tmux session 的屏幕状态；例如 `/tmux-screen 5s` 或 `/tmux-screen 120 5s`，最低 3 秒',
    '- `/tmux-screen stop` 停止当前聊天的 tmux 屏幕定时刷新',
    '- `/pty-screen [lines] [seconds]s` 查看当前 Codex pty Provider 或 Claude Code pty 的屏幕输出；例如 `/pty-screen 120 5s`，最低 3 秒',
    '- `/pty-screen stop` 停止当前聊天的 pty 屏幕定时刷新',
    '- `/tmux pwd<Enter>` 向当前 tmux session 发送按键并自动截屏返回',
    '- `/cat <path> [start] [end]` 打印文件内容（默认前 200 行）',
    '- `/file <path>` 发送本地文件；超过 20 MB 时先发确认卡，确认后后台上传并回链接',
    '',
    '**SessionRuntime 配置**',
    '- `/runtime codex|claude|kimi|cursor` 切换当前会话使用 Codex、Claude Code、Kimi Code 或 Cursor Agent；不会改变对应 runtime 已记住的 `/provider` 选择',
    '- `/m` 查看 YOLO模式；可用 `normal | yolo`，YOLO模式允许 agent 无需审批绕过沙箱',
    '- `/r` 查看 Codex 思考级别；可用 `1 | 2 | 3 | 4 | 5`',
    '- `/sb` 查看或切换 Codex 沙箱；可用 `read-only | workspace-write | danger-full-access | default`',
    '- `/net` 查看或切换 Codex 网络；可用 `on | off | default`',
    '- `/model` 查看当前模型；`/model gpt-5.4` 可切换，`/model default` 回退到默认模型',
    '- `/cd <path>` 替换当前会话工作目录；支持绝对路径、相对路径和 `~`',
    '',
    '**GlobalRuntime 配置**',
    '- `/set` 打开 TOML 配置卡片；顶部下拉切换「通用配置 / [runtime.codex] Codex / [runtime.claude] Claude / [runtime.kimi] Kimi / [runtime.cursor] Cursor / Bridge / 通道配置（feishu-default）」',
    '- `/set runtime codex|claude|kimi|cursor` 修改默认 agent `runtime.agent`（兼容旧名 `defaultRuntime`）',
    '- `/set defaultModel|defaultMode|codexSandboxMode|codexNetworkAccess|codexReasoningEffort ...` 修改 Codex 配置',
    '- `/set claudeProvider|claudeExecutable|claudeDefaultModel|claudeReasoningEffort|claudeIdleTimeoutMinutes ...` 修改 Claude 配置；Claude 可用 `pty | tmux | sdk`，Claude Router 可选 `claude` 或 `ccr`',
    '- `/set kimiProvider|kimiDefaultModel ...` 修改 Kimi 配置；Kimi 当前只支持 `tmux` Provider',
    '',
    '**GlobalBridge 配置**',
    '- `/set defaultWorkspaceRoot|tmuxCaptureLines|tmuxEchoInput ...` 修改通用配置；`/set uiAllowLan|uiAccessToken ...` 修改 Bridge；`/set historyMessageLimit ...` 修改通道配置',
    '- `/ui` 查看当前 UI 显示策略；工具详情始终显示',
    '',
    '**自动化**',
    '- `/every <数字><s|m|h|d> <prompt>` 创建定时输入；每次触发都会复用创建时绑定的当前会话',
    '- `/every` 查看当前聊天的定时输入表，`/every no <序号>` 取消',
    '- `/then <prompt>` 在当前会话 completed/interrupted 后发送一次后续输入；`/then` 查看待发送 prompt 并可用卡片新建、修改、取消',
    '- `/then set <序号> <prompt>` 修改 pending 后续输入；`/then no <序号>` 删除 pending 或中止 running',
  ].join('\n');
}
